### ISSUE TITLE
name attribute

### ISSUE THREAD

**Issue by kermorgant** [Gomah/vue-places#13]
Hello,

First, thanks for this nice component !

I'm using it on an old form and the generated input field is lacking a name attribute. Instead of reworking the whole thing, I've just put a hidden field bound to the right property fed by algolia.

Instead of having this workaround, would it be possible to have a name prop/option so that the shown value would be submitted with the rest of the form ?

**Comment by Gomah** [comment]
Hi @kermorgant,

Passing the `name` attribute to the component does not work for you ?

```vue
<places
  name="city"
  placeholder="Where are we going ?"
  v-model="form.country.label"
  @change="val => { form.country.data = val }"
  :options="{ countries: ['US'] }">
</places>
```

Here's the generated input field with the code above:

```html
<input data-v-5ffafb9a="" type="search" name="city" placeholder="Where are we going ?" class="ap-input" autocomplete="off" spellcheck="false" role="combobox" aria-autocomplete="both" aria-expanded="false" aria-owns="algolia-places-listbox-1" dir="auto" style="position: relative; vertical-align: top;">
```

If this does not work for you, would you mind sharing your Vue version & a snippet of your code?

**Comment by kermorgant** [comment]
Hi,
Thanks, it works fine ! In fact, looking at the component source, I just didn't think it could work that way. Maybe I've missed something but it looks like an implicit behaviour I have still to learn about...
